import type { ArchiveCase } from "./types";
import { youtubeThumbUrl } from "./thumbnails";

type DemoSeed = Omit<
  ArchiveCase,
  | "view_count"
  | "like_count"
  | "dislike_count"
  | "comment_count"
  | "share_count"
> &
  Partial<
    Pick<
      ArchiveCase,
      | "view_count"
      | "like_count"
      | "dislike_count"
      | "comment_count"
      | "share_count"
    >
  >;

const SEEDS: DemoSeed[] = [
  {
    id: "c1",
    slug: "ctg-open-snatching-kotwali",
    title: "চট্টগ্রামের কোতোয়ালীতে দিনদুপুরে প্রকাশ্যে ছিনতাই",
    district: "চট্টগ্রাম",
    thana: "কোতোয়ালী",
    crime_category: "snatching",
    date: "১৭ সেপ্টেম্বর ২০২৬",
    dur: "1:42",
    status: "reported",
    views: "৩.১ লাখ",
    view_count: 312000,
    like_count: 4800,
    comment_count: 1100,
    trend: true,
    media_provider: "youtube",
    media_embed_id: "yyHikN-rvjM",
    media_url: "https://www.youtube.com/watch?v=yyHikN-rvjM",
    summary:
      "চট্টগ্রামের কোতোয়ালী এলাকায় দিনদুপুরে প্রকাশ্যে ছিনতাইয়ের ঘটনা যমুনা টিভির ক্যামেরায় ধরা পড়ে।",
    timeline: [
      { s: "রিপোর্ট হয়েছে", d: "১৭ সেপ্টেম্বর ২০২৬", done: true },
      { s: "তদন্ত চলছে", d: "—", done: false },
      { s: "অভিযোগপত্র", d: "—", done: false },
      { s: "রায়", d: "—", done: false },
    ],
    sources: [{ t: "যাচাইকৃত নিউজ ভিডিও সূত্র", p: "Jamuna TV" }],
  },
  {
    id: "c2",
    slug: "transport-extortion-chadabaji",
    title: "পরিবহন নেতাদের আশীর্বাদে সড়কে অবাধ চাঁদাবাজি",
    district: "ঢাকা",
    crime_category: "corruption",
    date: "৮ সেপ্টেম্বর ২০২৬",
    dur: "4:20",
    status: "reported",
    views: "৪.২ লাখ",
    view_count: 420000,
    like_count: 7200,
    comment_count: 1900,
    trend: true,
    media_provider: "youtube",
    media_embed_id: "es-X8dvc2Uo",
    media_url: "https://www.youtube.com/watch?v=es-X8dvc2Uo",
    summary:
      "সড়কে পরিবহন খাতে চাঁদাবাজির অভিযোগ নিয়ে সময় টিভির অনুসন্ধানী প্রতিবেদন।",
    timeline: [
      { s: "রিপোর্ট হয়েছে", d: "৮ সেপ্টেম্বর ২০২৬", done: true },
      { s: "তদন্ত চলছে", d: "—", done: false },
      { s: "অভিযোগপত্র", d: "—", done: false },
      { s: "রায়", d: "—", done: false },
    ],
    sources: [{ t: "যাচাইকৃত নিউজ ভিডিও সূত্র", p: "SOMOY TV" }],
  },
  {
    id: "c3",
    slug: "faridpur-sexual-violence-life-sentence",
    title: "ফরিদপুরে যৌন নির্যাতনের দায়ে শ্বশুরের যাবজ্জীবন কারাদণ্ড",
    district: "ফরিদপুর",
    crime_category: "sexual_violence",
    date: "১১ আগস্ট ২০২৬",
    dur: "2:55",
    status: "convicted",
    views: "১.৯ লাখ",
    view_count: 198000,
    like_count: 3100,
    comment_count: 890,
    official: true,
    media_provider: "youtube",
    media_embed_id: "nBnR2WDBFIU",
    media_url: "https://www.youtube.com/watch?v=nBnR2WDBFIU",
    summary:
      "ফরিদপুরে পুত্রবধূকে যৌন নির্যাতনের মামলায় শ্বশুরকে যাবজ্জীবন কারাদণ্ড দিয়েছে আদালত।",
    timeline: [
      { s: "রিপোর্ট হয়েছে", d: "জানু ২০২৫", done: true },
      { s: "তদন্ত চলছে", d: "মার্চ ২০২৫", done: true },
      { s: "অভিযোগপত্র", d: "জুন ২০২৫", done: true },
      { s: "রায় — দণ্ডিত", d: "১১ আগস্ট ২০২৬", done: true },
    ],
    sources: [{ t: "যাচাইকৃত নিউজ ভিডিও সূত্র", p: "Jamuna TV" }],
  },
  {
    id: "c4",
    slug: "pabna-koli-murder",
    title: "পাবনায় কলি হত্যাকাণ্ড — অভিযুক্তের বাড়িতে ভাঙচুরের খবর",
    district: "পাবনা",
    crime_category: "murder",
    date: "১৭ সেপ্টেম্বর ২০২৬",
    dur: "3:10",
    status: "under_investigation",
    views: "১.৭ লাখ",
    view_count: 176000,
    like_count: 2800,
    comment_count: 890,
    trend: true,
    media_provider: "youtube",
    media_embed_id: "gd-agOPDljY",
    media_url: "https://www.youtube.com/watch?v=gd-agOPDljY",
    summary:
      "পাবনায় কলি হত্যাকাণ্ডের ঘটনায় অভিযুক্ত প্রতিবেশীর বাড়িতে স্থানীয়দের ভাঙচুরের খবর।",
    timeline: [
      { s: "রিপোর্ট হয়েছে", d: "১৭ সেপ্টেম্বর ২০২৬", done: true },
      { s: "তদন্ত চলছে", d: "১৮ সেপ্টেম্বর ২০২৬", done: true },
      { s: "অভিযোগপত্র", d: "—", done: false },
      { s: "রায়", d: "—", done: false },
    ],
    sources: [{ t: "যাচাইকৃত নিউজ ভিডিও সূত্র", p: "Jamuna TV" }],
  },
  {
    id: "c5",
    slug: "tangail-bus-robbery-harassment",
    title: "টাঙ্গাইলে বাসে ডাকাতি ও শ্লীলতাহানি, মূল পরিকল্পনাকারী গ্রেফতার",
    district: "টাঙ্গাইল",
    crime_category: "harassment",
    date: "৬ সেপ্টেম্বর ২০২৬",
    dur: "3:40",
    status: "under_investigation",
    views: "২.৮ লাখ",
    view_count: 285000,
    like_count: 4200,
    comment_count: 980,
    media_provider: "youtube",
    media_embed_id: "ne79xeZ03V0",
    media_url: "https://www.youtube.com/watch?v=ne79xeZ03V0",
    summary:
      "টাঙ্গাইলে বাসে ডাকাতি ও নারী যাত্রীদের শ্লীলতাহানির ঘটনায় পুলিশ জড়িতদের গ্রেফতার করেছে।",
    timeline: [
      { s: "রিপোর্ট হয়েছে", d: "৬ সেপ্টেম্বর ২০২৬", done: true },
      { s: "তদন্ত চলছে", d: "৭ সেপ্টেম্বর ২০২৬", done: true },
      { s: "অভিযোগপত্র", d: "—", done: false },
      { s: "রায়", d: "—", done: false },
    ],
    sources: [{ t: "যাচাইকৃত নিউজ ভিডিও সূত্র", p: "Jamuna TV" }],
  },
  {
    id: "c6",
    slug: "uttara-student-kidnap-ransom",
    title: "অপহরণের পর নির্যাতনের ভিডিও পাঠিয়ে মুক্তিপণ দাবি",
    district: "ঢাকা",
    upazila: "উত্তরা",
    crime_category: "kidnapping",
    date: "৯ সেপ্টেম্বর ২০২৬",
    dur: "2:48",
    status: "charged",
    views: "৫.২ লাখ",
    view_count: 520000,
    like_count: 8100,
    comment_count: 2700,
    trend: true,
    media_provider: "youtube",
    media_embed_id: "bqpcoYoqXfM",
    media_url: "https://www.youtube.com/watch?v=bqpcoYoqXfM",
    summary:
      "উত্তরায় শিক্ষার্থী অপহরণের পর নির্যাতনের ভিডিও পাঠিয়ে মুক্তিপণ দাবির ঘটনা।",
    timeline: [
      { s: "রিপোর্ট হয়েছে", d: "৯ সেপ্টেম্বর ২০২৬", done: true },
      { s: "তদন্ত চলছে", d: "১০ সেপ্টেম্বর ২০২৬", done: true },
      { s: "অভিযোগপত্র", d: "১২ সেপ্টেম্বর ২০২৬", done: true },
      { s: "রায়", d: "—", done: false },
    ],
    sources: [{ t: "যাচাইকৃত নিউজ ভিডিও সূত্র", p: "Jamuna TV" }],
  },
  {
    id: "c7",
    slug: "boesel-mobile-banking-scam",
    title: "বোয়েসেলের নামে প্রতারণা — বিকাশে টাকা উধাও",
    district: "ঢাকা",
    crime_category: "fraud",
    date: "১৩ সেপ্টেম্বর ২০২৬",
    dur: "2:20",
    status: "under_investigation",
    views: "৩.৭ লাখ",
    view_count: 378000,
    like_count: 5600,
    comment_count: 1400,
    media_provider: "youtube",
    media_embed_id: "P1ODSobLxFs",
    media_url: "https://www.youtube.com/watch?v=P1ODSobLxFs",
    summary:
      "বোয়েসেলের নামে অনলাইন প্রতারণার ফাঁদে পড়ে বিকাশ থেকে টাকা উধাও হওয়ার অভিযোগ।",
    timeline: [
      { s: "রিপোর্ট হয়েছে", d: "১৩ সেপ্টেম্বর ২০২৬", done: true },
      { s: "তদন্ত চলছে", d: "১৪ সেপ্টেম্বর ২০২৬", done: true },
      { s: "অভিযোগপত্র", d: "—", done: false },
      { s: "রায়", d: "—", done: false },
    ],
    sources: [{ t: "যাচাইকৃত নিউজ ভিডিও সূত্র", p: "Jamuna TV" }],
  },
  {
    id: "c8",
    slug: "crime-scene-generational-dacoit",
    title: "৩ প্রজন্ম ধরে ডাকাত — এক ডাকাতিতেই কোটি টাকার বাণিজ্য",
    district: "ঢাকা",
    crime_category: "robbery",
    date: "১৪ সেপ্টেম্বর ২০২৬",
    dur: "18:00",
    status: "trial_ongoing",
    views: "৮.৯ লাখ",
    view_count: 890000,
    like_count: 12000,
    comment_count: 3400,
    trend: true,
    media_provider: "youtube",
    media_embed_id: "BkcuVO2olq4",
    media_url: "https://www.youtube.com/watch?v=BkcuVO2olq4",
    summary:
      "যমুনা টিভির ক্রাইম সিনে তিন প্রজন্ম ধরে ডাকাতির সঙ্গে জড়িত চক্র নিয়ে অনুসন্ধান।",
    timeline: [
      { s: "রিপোর্ট হয়েছে", d: "২০২৪", done: true },
      { s: "তদন্ত চলছে", d: "২০২৫", done: true },
      { s: "অভিযোগপত্র", d: "২০২৫", done: true },
      { s: "রায়", d: "বিচারাধীন", done: false },
    ],
    sources: [{ t: "যাচাইকৃত নিউজ ভিডিও সূত্র", p: "Jamuna TV" }],
  },
    {
    id: "c9",
    slug: "fb-player-test-public-1",
    title: "[Facebook] প্লেয়ার টেস্ট — পাবলিক ভিডিও এম্বেড",
    district: "ঢাকা",
    crime_category: "other",
    date: "১৯ সেপ্টেম্বর ২০২৬",
    dur: "1:00",
    status: "reported",
    views: "৪৫ হাজার",
    view_count: 45000,
    like_count: 620,
    comment_count: 88,
    media_provider: "facebook",
    media_embed_id: "10153231379946729",
    media_url: "https://www.facebook.com/facebook/videos/10153231379946729/",
    summary:
      "Facebook ভিডিও প্লেয়ার যাচাই — পাবলিক Facebook ভিডিও এম্বেড। YouTube কেসের পাশে তুলনা করুন।",
    timeline: [
      { s: "রিপোর্ট হয়েছে", d: "১৯ সেপ্টেম্বর ২০২৬", done: true },
      { s: "তদন্ত চলছে", d: "—", done: false },
      { s: "অভিযোগপত্র", d: "—", done: false },
      { s: "রায়", d: "—", done: false },
    ],
    sources: [{ t: "Facebook এম্বেড সূত্র", p: "Facebook" }],
  },
  {
    id: "c10",
    slug: "fb-player-test-public-2",
    title: "[Facebook] দ্বিতীয় এম্বেড — watch/?v= ফরম্যাট",
    district: "চট্টগ্রাম",
    crime_category: "fraud",
    date: "১৮ সেপ্টেম্বর ২০২৬",
    dur: "0:45",
    status: "reported",
    views: "৩৮ হাজার",
    view_count: 38000,
    like_count: 510,
    comment_count: 64,
    media_provider: "facebook",
    media_embed_id: "10155554431506803",
    media_url: "https://www.facebook.com/watch/?v=10155554431506803",
    summary:
      "অন্য পাবলিক Facebook ভিডিও — watch URL ফরম্যাট। প্লেয়ার ও নতুন-ট্যাব ফলব্যাক চেক করুন।",
    timeline: [
      { s: "রিপোর্ট হয়েছে", d: "১৮ সেপ্টেম্বর ২০২৬", done: true },
      { s: "তদন্ত চলছে", d: "—", done: false },
      { s: "অভিযোগপত্র", d: "—", done: false },
      { s: "রায়", d: "—", done: false },
    ],
    sources: [{ t: "Facebook এম্বেড সূত্র", p: "Facebook" }],
  },
];

export const DEMO_CASES: ArchiveCase[] = SEEDS.map((s) => ({
  dislike_count: 0,
  share_count: 0,
  view_count: s.view_count ?? 0,
  like_count: s.like_count ?? 0,
  comment_count: s.comment_count ?? 0,
  thumbnail_url:
    s.thumbnail_url ||
    (s.media_provider === "youtube" && s.media_embed_id
      ? youtubeThumbUrl(s.media_embed_id)
      : undefined),
  ...s,
}));
